# APP DEPLOYMENT
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: shipper
  name: shipper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipper
  template:
    metadata:
      labels:
        app: shipper
    spec:
      containers:
      - env:
        - name: KAFKA_ORDER_PICKED
          value: "soaring-soaring-orderpicked"
        - name: KAFKA_SHIPMENT_REQUEST_ISSUED_TOPIC
          value: "soaring-shipmentrequestissued"
        - name: KAFKA_BROKER
          value: "18.184.145.38:9092"
        - name: KAFKA_REGISTRY
          value: "http://18.184.145.38:18081"
        - name: SHIPPERMARKET_URL
          value: "http://130.61.20.66"
        image: lonneke/shipper:1.0
        name: shipper
        ports:
        - containerPort: 7070
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipper
  name: portal
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 7070
  selector:
    app: portal
  type: NodePort
