apiVersion: v1
kind: Service
metadata:
  name: shipping-backend-ms
  labels:
    app: shipping-backend-ms
spec:
  type: LoadBalancer
  selector:
    app: shipping-backend-ms
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-backend-ms
spec:
  selector:
    matchLabels:
      app: shipping-backend-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping-backend-ms
    spec:
      containers:
      - name: shipping-backend-ms
        image: lonneke/shipping-backend-ms:1.1.3
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: BLOCKCHAINURL
          value: "https://130.61.43.110:22018/"
        - name: RESTPROXY
          value: "restproxy1"
        - name: USERNAME
          value: "customertenant@oracle.com"
        - name: PASSWORD
          value: "Welcome1"
        - name: LOG_LEVEL
          value: "debug"
        - name: PORT
          value: "8070"
        - name: CHANNEL
          value: "testshipping"
        - name: CHAINCODE
          value: "shipment"
        - name: VERSION
          value: "1.1.1"
        - name: KAFKA_BROKER
          value: "18.184.145.38:9092"
        - name: KAFKA_REGISTRY
          value: "http://18.184.145.38:18081"
        - name: PUBLISH
          value: "true"
        - name: KAFKA_SHIPMENT_OFFER_TOPIC 
          value: "soaring-shipmentoffer"
        - name: KAFKA_SHIPMENT_PICKEDUP_TOPIC
          value: "soaring-shipmentpickedup"
        - name: KAFKA_SHIPMENT_RECEIVED_TOPIC
          value: "soaring-shipmentreceived"
        - name: KAFKA_SHIPMENT_REQUEST_ISSUED_TOPIC
          value: "soaring-shipmentrequestissued" 
        ports: 
        - name: http
          containerPort: 8070